
const char html_page_reboot[] PROGMEM =
"<p>_TXT_M_REBOOT_ <span id='count'>10s</span>...</p>"
;

const char html_page_reset[] PROGMEM =
"<p>_TXT_M_RESET_ _SSID_...</p>"
;

const char html_page_save_reboot[] PROGMEM =
"<p>_TXT_M_SAVE_ <span id='count'>10s</span>...</p>"
;

const char html_page_mqtt[] PROGMEM =
"<div id='l1' name='l1'>"
    "<fieldset>"
        "<legend><b>&nbsp; _TXT_MQTT_TITLE_ &nbsp;</b></legend>"
        "<form method='post'>"
            "<p><b>_TXT_MQTT_FN_</b>"
                "<br/>"
                "<input id='fn' name='fn' "
                "autocomplete='off' autocorrect='off' autocapitalize='off' spellcheck='false' "
                "placeholder=' ' value='_MQTT_FN_'>"
            "</p>"
            "<p><b>_TXT_MQTT_HOST_</b>"
                "<br/>"
                "<input id='mh' name='mh' "
                "autocomplete='off' autocorrect='off' autocapitalize='off' spellcheck='false' "
                "placeholder=' ' value='_MQTT_HOST_'>"
            "</p>"
            "<p><b>_TXT_MQTT_PORT_</b>"
                "<br/>"
                "<input id='ml' name='ml' type='numeric' placeholder='1883' value='_MQTT_PORT_'>"
            "</p>"
            "<p><b>_TXT_MQTT_USER_</b>"
                "<br/>"
                "<input id='mu' name='mu' "
                "autocomplete='off' autocorrect='off' autocapitalize='off' spellcheck='false' "
                "placeholder='DVES_USER' value='_MQTT_USER_'>"
            "</p>"
            "<p><b>_TXT_MQTT_PASSWORD_</b>"
                "<br/>"
                "<input id='mp' name='mp' type='password' placeholder='Password' value='_MQTT_PASSWORD_'>"
            "</p>"
            "<p><b>_TXT_MQTT_TOPIC_</b>"
                "<br/>"
                "<input id='mt' name='mt' "
                "autocomplete='off' autocorrect='off' autocapitalize='off' spellcheck='false' "
                "placeholder='topic' value='_MQTT_TOPIC_'>"
            "</p>"
            "<br/>"
            "<button name='save' type='submit' class='button bgrn'>_TXT_SAVE_</button>"
        "</form>"
    "</fieldset>"
    "<p>"
        "<a class='button back' href='/setup'>_TXT_BACK_</a>"
    "</p>"
"</div>"
;


const char html_page_telegram[] PROGMEM =
"<div id='l1' name='l1'>"
    "<fieldset>"
        "<legend><b>&nbsp; _TXT_TELEGRAM_TITLE_ &nbsp;</b></legend>"
        "<form method='post'>"
            "<p><b>_TXT_TELEGRAM_CHAT_ID_</b>"
                "<br/>"
                "<input id='tci' name='tci' "
                "autocomplete='off' autocorrect='off' autocapitalize='off' spellcheck='false' "
                "placeholder=' ' value='_TELEGRAM_CHAT_ID_'>"
            "</p>"
            "<p><b>_TXT_TELEGRAM_BOT_TOKEN_</b>"
                "<br/>"
                "<input id='tbt' name='tbt' "
                "autocomplete='off' autocorrect='off' autocapitalize='off' spellcheck='false' "
                "placeholder=' ' value='_TELEGRAM_BOT_TOKEN_'>"
            "</p>"
            "<br/>"
            "<button name='save' type='submit' class='button bgrn'>_TXT_SAVE_</button>"
        "</form>"
    "</fieldset>"
    "<p>"
        "<a class='button back' href='/setup'>_TXT_BACK_</a>"
    "</p>"
"</div>"
;


const char html_page_temperature[] PROGMEM =
"<div id='l1' name='l1'>"
    "<fieldset>"
        "<legend><b>&nbsp; _TXT_TEMPERATURE_TITLE_ &nbsp;</b></legend>"
        "<form method='post'>"
            "<p><b>_TXT_TEMPERATURE_SENSOR_</b>"
                "<select name='sensor_pin'>"
                    "<option value='SENSOR_P0' _SENSOR_P0_>_TXT_P0_</option>"
                    "<option value='SENSOR_P1' _SENSOR_P1_>_TXT_P1_</option>"
                    "<option value='SENSOR_P2' _SENSOR_P2_>_TXT_P2_</option>"
                    "<option value='SENSOR_P3' _SENSOR_P3_>_TXT_P3_</option>"
                    "<option value='SENSOR_P4' _SENSOR_P4_>_TXT_P4_</option>"
                    "<option value='SENSOR_P5' _SENSOR_P5_>_TXT_P5_</option>"
                    "<option value='SENSOR_P6' _SENSOR_P6_>_TXT_P6_</option>"
                    "<option value='SENSOR_P7' _SENSOR_P7_>_TXT_P7_</option>"
                    "<option value='SENSOR_P8' _SENSOR_P8_>_TXT_P8_</option>"
                    "<option value='SENSOR_TX' _SENSOR_TX_>_TXT_TX_</option>"
                    "<option value='SENSOR_RX' _SENSOR_RX_>_TXT_RX_</option>"
                "</select>"
            "</p>"
            "<p><b>_TXT_TEMPERATURE_LIMIT_</b>"
                "<br/>"
                "<input id='temp_limit' name='temp_limit' "
                "autocomplete='off' autocorrect='off' autocapitalize='off' spellcheck='false' "
                "placeholder=' ' value='_TEMPERATURE_LIMIT_'>"
            "</p>"
            "<p><b>_TXT_TEMPERATURE_RELAY_</b>"
                "<select name='relay_pin'>"
                    "<option value='RELAY_P0' _RELAY_P0_>_TXT_P0_</option>"
                    "<option value='RELAY_P1' _RELAY_P1_>_TXT_P1_</option>"
                    "<option value='RELAY_P2' _RELAY_P2_>_TXT_P2_</option>"
                    "<option value='RELAY_P3' _RELAY_P3_>_TXT_P3_</option>"
                    "<option value='RELAY_P4' _RELAY_P4_>_TXT_P4_</option>"
                    "<option value='RELAY_P5' _RELAY_P5_>_TXT_P5_</option>"
                    "<option value='RELAY_P6' _RELAY_P6_>_TXT_P6_</option>"
                    "<option value='RELAY_P7' _RELAY_P7_>_TXT_P7_</option>"
                    "<option value='RELAY_P8' _RELAY_P8_>_TXT_P8_</option>"
                    "<option value='RELAY_TX' _RELAY_TX_>_TXT_TX_</option>"
                    "<option value='RELAY_RX' _RELAY_RX_>_TXT_RX_</option>"
                "</select>"
            "</p>"
            "<br/>"
            "<button name='save' type='submit' class='button bgrn'>_TXT_SAVE_</button>"
        "</form>"
    "</fieldset>"
    "<p>"
        "<a class='button back' href='/setup'>_TXT_BACK_</a>"
    "</p>"
"</div>"
;


const char html_page_others[] PROGMEM =
"<div id='l1' name='l1'>"
    "<fieldset>"
        "<legend><b>&nbsp; _TXT_OTHERS_TITLE_ &nbsp;</b></legend>"
        "<form method='post'>"
            "<p><b>_TXT_OTHERS_HAAUTO_</b>"
                "<select name='haad'>"
                    "<option value='ON' _HAAD_ON_>_TXT_ON_</option>"
                    "<option value='OFF' _HAAD_OFF_>_TXT_OFF_</option>"
                "</select>"
            "</p>"
            "<p><b>_TXT_OTHERS_HATOPIC_</b>"
                "<br/>"
                "<input id='haat' name='haat' "
                "autocomplete='off' autocorrect='off' autocapitalize='off' spellcheck='false' "
                "placeholder=' ' value='_HAA_TOPIC_'>"
            "</p>"
            "<p><b>_TXT_OTHERS_DEBUG_</b>"
                "<select name='debug'>"
                    "<option value='ON' _DEBUG_ON_>_TXT_ON_</option>"
                    "<option value='OFF' _DEBUG_OFF_>_TXT_OFF_</option>"
                "</select>"
            "</p>"
            "<br/>"
            "<button name='save' type='submit' class='button bgrn'>_TXT_SAVE_</button>"
        "</form>"
    "</fieldset>"
        "<fieldset>"
        "<legend><b>&nbsp; _TXT_OTHERS_LOG_ &nbsp;</b></legend>"
           "<p>"
            "_DEBUG_CONSOLE_"
          "</p>"
        "</fieldset>"
    "<p>"
        "<a class='button back' href='/setup'>_TXT_BACK_</a>"
    "</p>"
"</div>"
;


const char html_page_status[] PROGMEM =
"<div id='l1' name='l1'>"
    "<fieldset>"
    "<legend><b>&nbsp; _TXT_STATUS_TITLE_ &nbsp;</b></legend>"
    "<p><b>_TXT_TEMPERATURE_</b>"
        ": "
        "_CURRENT_TEMPERATURE_"
    "</p>"
    "<p><b>_TXT_HUMIDITY_</b>"
        ": "
        "_CURRENT_HUMIDITY_"
    "</p>"
    "<p><b>_TXT_STATUS_TEMPERATURE_</b>"
        ": "
        "_TEMPERATURE_STATUS_"
    "</p>"
    "<p><b>_TXT_STATUS_TELEGRAM_</b>"
        ": "
        "_TELEGRAM_STATUS_"
    "</p>"
     "<p><b>_TXT_STATUS_MQTT_</b>"
        ": " 
        "_MQTT_STATUS_ (_MQTT_REASON_)"
    "</p>"
     "<p><b>_TXT_STATUS_WIFI_</b>"
        ":"
        "_WIFI_STATUS_ dBm"
    "</p>"
    "</fieldset>"
    "<br />"
    "<p>"
        "<a class='button back' href='/'>_TXT_BACK_</a>"
    "</p>"
"</div>"
;

const char html_page_wifi[] PROGMEM =
"<div id='l1' name='l1'>"
    "<fieldset>"
        "<legend><b>&nbsp; _TXT_WIFI_TITLE_ &nbsp;</b></legend>"
        "<form method='post'>"
            "<p><b>_TXT_WIFI_HOST_</b>"
                "<br/>"
                "<input id='hn' "
                "autocomplete='off' autocorrect='off' autocapitalize='off' spellcheck='false' "
                " name='hn' placeholder=' ' value='_UNIT_NAME_'>"
            "</p>"
            "<p><b>_TXT_WIFI_SSID_</b>"
                "<br/>"
                "<input id='ssid' "
                "autocomplete='off' autocorrect='off' autocapitalize='off' spellcheck='false' "
                "name='ssid' placeholder=' ' value='_SSID_'>"
            "</p>"
            "<p><b>_TXT_WIFI_PSK_</b>"
                "<br/>"
                "<input id='psk' type='password' name='psk' placeholder=' ' value='_PSK_'>"
            "</p>"
            "<p><b>_TXT_WIFI_OTAP_</b>"
                "<br/>"
                "<input id='otapwd' "
                "autocomplete='off' autocorrect='off' autocapitalize='off' spellcheck='false' "
                "name='otapwd' placeholder=' ' value='_OTA_PWD_'>"
            "</p>"
            "<br/>"
            "<button name='save' type='submit' class='button bgrn'>_TXT_SAVE_</button>"
        "</form>"
    "</fieldset>"
    "<p>"
        "<a class='button back' href='/setup'>_TXT_BACK_</a>"
    "</p>"
"</div>"
;


const char html_page_login[] PROGMEM =
"<script>"
    "var loginSucess = _LOGIN_SUCCESS_;"
    "document.onreadystatechange = function() {"
        "if (document.readyState === 'complete') {"
            "if (loginSucess == 1) {"
                "var element = document.getElementById('login_form');"
                "element.parentNode.removeChild(element);"
            "}"
        "}"
    "}"
"</script>"
"<div id='login_form' name='login_form'>"
    "<fieldset>"
        "<legend><b>&nbsp; _TXT_LOGIN_TITLE_ &nbsp;</b></legend>"
        "<form action='/login' method='post'>"
            "<!--<p>To log in, enter user: <b>admin</b> and password</p>"
            "<p><b>User</b>-->"
                "<input type='hidden' name='USERNAME' placeholder='user name' value='admin'>"
            "</p>"
            "<p><b>_TXT_LOGIN_PASSWORD_</b>"
                "<input type='password' name='PASSWORD' placeholder='_TXT_LOGIN_PASSWORD_'>"
            "</p>"
            "<br/>"
            "<button name='SUBMIT' type='submit' class='button bgrn'>_TXT_LOGIN_</button>"
        "</form>"
        "<!-- <br> You can go to <a href='/status'>status page</a>-->"
        "<br>"
    "</fieldset>"
"</div>"
"<div>"
    "_LOGIN_MSG_"
"</div>"
;

const char html_page_upgrade[] PROGMEM =
"<script>"
    "function eb(s) {"
        "return document.getElementById(s);"
    "}"
"</script>"
    "<div id='f1' style='display:block;'>"
        "<fieldset>"
            "<legend><b>&nbsp; _TXT_UPGRADE_TITLE_ &nbsp;</b></legend>"
            "<form method='post' action='upload' enctype='multipart/form-data'>"
                "<p><span>_TXT_UPGRADE_INFO_</span></p>"
                "<br>"
                "<input type='file' accept='.bin' name='upload'>"
                "<br>"
                "<br>"
                "<button type='submit' onclick=\"eb('f1').style.display='none';eb('f2').style.display='block';this.form.submit();\" class='button bgrn'>_TXT_B_UPGRADE_</button>"
            "</form>"
        "</fieldset>"
        "<p>"
            "<a class='button back' href='/'>_TXT_BACK_</a>"
        "</p>"
    "</div>"
    "<div id='f2' style='display:none;text-align:center;'><b>_TXT_UPGRADE_START_ ...</b></div>"
;


const char html_page_upload[] PROGMEM =
"<div id='l1' name='l1'>"
    "<br>_UPLOAD_MSG_"
    "<p>"
        "<a class='button back' href='/upgrade'>_TXT_BACK_</a>"
    "</p>"
"</div>"
;
